name: Send BBC News to Kindle

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Calibre
        run: |
          sudo apt-get update
          sudo apt-get install -y calibre

      - name: Build BBC EPUB
        run: |
          ebook-convert bbc.recipe bbc.epub --output-profile kindle

      - name: Send EPUB to Kindle via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP }}
          server_port: ${{ secrets.PORT }}
          username: ${{ secrets.FROM }}
          password: ${{ secrets.SECRET }}
          subject: "BBC News - ${{ github.sha }}"
          to: ${{ secrets.TO }}
          from: ${{ secrets.FROM }}
          attachments: bbc.epub
